-- VAL TAKES THE RESERVATION.
--
-- Recovered into the repo from the deployed definitions: this went to the
-- database across four ad-hoc migrations during the session that built the
-- booking, and none of the SQL was written here. Consolidated into one file
-- so the table can be rebuilt from the repository alone.
--
-- The rule this table exists to keep: the confirmation the visitor sees must
-- describe a row that exists. The reference and the timestamp both come back
-- FROM here — they are not generated in the browser and drawn on the screen.
--
-- Row-level security is ON and there are deliberately NO policies. Nothing
-- reaches this table except through the security-definer functions below,
-- each of which decides exactly how much it is willing to say.

create table if not exists public.live_rsvps (
  id        bigint generated by default as identity primary key,
  ref       text not null unique,
  name      text not null,
  cell      text not null default '',
  attend    text not null default 'in-person',
  note      text not null default '',
  at        timestamptz not null default now(),
  show_name boolean not null default false,
  brokerage text not null default '',
  bringing  text not null default ''
);

alter table public.live_rsvps enable row level security;

create index if not exists live_rsvps_at_idx on public.live_rsvps (at desc);

-- WRITE. Idempotent on the reference, so a retry from a flaky phone is the
-- same seat and not a second one.
create or replace function public.live_rsvp_add(
  p_ref text, p_name text, p_cell text, p_attend text, p_note text
) returns timestamptz language plpgsql security definer set search_path to 'public' as $$
declare t timestamptz; n bigint;
begin
  if coalesce(trim(p_name), '') = '' then raise exception 'need_name'; end if;
  if length(p_ref) < 4 or length(p_ref) > 24 then raise exception 'bad_ref'; end if;

  select at into t from live_rsvps where ref = p_ref;
  if t is not null then return t; end if;

  -- A blunt backstop on a public write: no more than 400 reservations an hour
  -- across the whole table. A real room fills long before that; a script does
  -- not get to fill the table.
  select count(*) into n from live_rsvps where at >= now() - interval '1 hour';
  if n >= 400 then raise exception 'too_many'; end if;

  insert into live_rsvps (ref, name, cell, attend, note)
  values (
    p_ref,
    left(trim(p_name), 80),
    left(trim(coalesce(p_cell, '')), 32),
    case when p_attend in ('in-person','zoom','either') then p_attend else 'in-person' end,
    left(trim(coalesce(p_note, '')), 400)
  )
  returning at into t;
  return t;
end $$;

-- READ, FOR THE PERSON HOLDING THE REFERENCE. First name and nothing else:
-- this is what /kit/[ref] greets somebody with, and a reference is not a
-- password, so it must never be able to hand back a phone number.
create or replace function public.live_rsvp_get(p_ref text)
returns table(who text, attend text, at timestamptz)
language plpgsql security definer set search_path to 'public' as $$
begin
  return query
    select split_part(trim(r.name), ' ', 1) as who, r.attend, r.at
      from live_rsvps r
     where r.ref = p_ref
     limit 1;
end $$;

-- CONSENT. Nothing is public until the person says so, in their own booking.
create or replace function public.live_rsvp_room(
  p_ref text, p_show boolean, p_brokerage text, p_bringing text
) returns boolean language plpgsql security definer set search_path to 'public' as $$
declare found boolean;
begin
  update live_rsvps
     set show_name = coalesce(p_show, false),
         brokerage = left(trim(coalesce(p_brokerage, '')), 60),
         bringing  = left(trim(coalesce(p_bringing, '')), 160)
   where ref = p_ref
  returning true into found;
  return coalesce(found, false);
end $$;

-- THE WALL. Consented names only, first name only.
create or replace function public.live_rsvp_wall()
returns table(who text, brokerage text, bringing boolean)
language plpgsql security definer set search_path to 'public' as $$
begin
  return query
    select
      -- First name only. A single-word name stays whole; anything longer is
      -- cut at the first space so a full legal name never lands on a page.
      split_part(trim(r.name), ' ', 1) as who,
      r.brokerage,
      (length(trim(r.bringing)) > 0) as bringing
    from live_rsvps r
    where r.show_name is true
      and length(trim(r.name)) > 0
    order by r.at desc
    limit 60;
end $$;

-- THE NUMBER. Counts every row as deployed; 011 benches selftest rows out of
-- it, because a seat count is a claim and must only ever count real people.
create or replace function public.live_rsvp_count()
returns bigint language plpgsql security definer set search_path to 'public' as $$
declare n bigint;
begin
  select count(*) into n from live_rsvps;
  return n;
end $$;

-- THE INBOX. Presenter only, and deliberately unfiltered.
create or replace function public.live_rsvp_list(p_key text)
returns setof live_rsvps language plpgsql security definer set search_path to 'public' as $$
begin
  if live_check_key(p_key) is distinct from 'presenter' then raise exception 'not_presenter'; end if;
  return query select * from live_rsvps order by at desc limit 500;
end $$;

grant execute on function public.live_rsvp_add(text, text, text, text, text) to anon, authenticated;
grant execute on function public.live_rsvp_get(text) to anon, authenticated;
grant execute on function public.live_rsvp_room(text, boolean, text, text) to anon, authenticated;
grant execute on function public.live_rsvp_wall() to anon, authenticated;
grant execute on function public.live_rsvp_count() to anon, authenticated;
grant execute on function public.live_rsvp_list(text) to anon, authenticated;
